/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2019-12-13 06:27:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html.vue.register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_html extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"icon\" href=\"images/title.icon\" type=\"images/x-icon\">\n");
      out.write("\t\t<title>登录注册</title>\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"author\" content=\"\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap/css/bootstrap.min.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap/css/bootstrap-theme.min.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/vue/register/register.css\" />\n");
      out.write("\t</head>\n");
      out.write("\t<body >\n");
      out.write("\t\t<div class=\"main\" >\n");
      out.write("\t\t\t<div class='registerTable'  id=\"app\" >\n");
      out.write("\t\t\t\t<div class=\"title\" >\n");
      out.write("\t\t\t\t\t<div class=\"login\" id=\"login\" @click=\"showLogin\">\n");
      out.write("\t\t\t\t\t\t<div class=\"login-text\">登录</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"line\" id=\"loginLine\" v-if=\"login\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"login\" id='register' @click=\"showRegister\">\n");
      out.write("\t\t\t\t\t\t<div class=\"login-text\">注册</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"line\" id=\"registerLine\" v-if=\"register\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"loginContent\"  v-if=\"login\">\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<div class=\"warnning\" v-cloak>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-warning-sign\" v-if=\"loginMessage\"></span>\n");
      out.write("\t\t\t\t\t\t\t<span>{{loginMessage}}</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<span>账号：</span>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" v-model.trim='userName'  class=\"formDiv-input\"/>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<span>密码：</span>\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"password\" v-model.trim=\"userPassWord\" id=\"password\"  class=\"formDiv-input\"/>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<canvas id=\"canvas\" width=\"100px\" height=\"40px\" style=\"float:left; margin-top: 5px;margin-left: 46px;\"></canvas>\n");
      out.write("\t\t\t\t\t\t<a class=\"giveNew\" @click=\"getCode\">换一张</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<span style=\"float:left;margin-left: -13px;\">验证码：</span>\n");
      out.write("\t\t\t\t\t\t<input style=\"margin-left:3px\" type=\"text\" name=\"verification\" id=\"verification\" v-model.trim=\"verification\"  class=\"formDiv-input\"/>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success myBotton\" @click='onLogin' :disabled=\"userName.length==0||userPassWord.length==0||verification.length==0\">登录</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div  class=\"loginContent\" v-cloak v-if=\"register\" style=\"margin-top: 0px;\">\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<div class=\"warnning\" v-if=\"messageRegister\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-warning-sign\" ></span>\n");
      out.write("\t\t\t\t\t\t\t<span>{{messageRegister}}</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<span>账号：</span>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" v-model=\"nameRegister\" value=\"nameRegister?nameRegister:''\"  class=\"formDiv-input\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<span>密码：</span>\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"passwordRegister\" id=\"passwordRegister\" v-model=\"passWordRegister\" value=\"passWordRegister\"  class=\"formDiv-input\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<span style=\"margin-left:-28px\">确认密码：</span>\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"passwordRegisterAffirm\" id=\"passwordRegisterAffirm\" v-model=\"passWordRegisterAffirm\" value=\"passWordRegisterAffirm\"  class=\"formDiv-input\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<span>邮箱：</span>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"password\" id=\"mailRegister\" v-model=\"mailRegister\" value=\"mailRegister\"  class=\"formDiv-input\" />\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success myBotton\" @click=\"submit\" :disabled=\"messageRegister.length!=0||nameRegister.length==0||passWordRegister.length==0||passWordRegisterAffirm.length==0||mailRegister.length==0\">注册</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("\t\n");
      out.write("\t<script src=\"javaScript/jquery/jquery-1.8.2.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("\t<script src=\"javaScript/vue/vue.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("\t<script src=\"javaScript/vue/resource.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("\t<script src=\"bootstrap/js/bootstrap.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("\t<script src=\"javaScript/vue/register/register.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\t\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
